# Generated by Django 5.1.2 on 2025-11-10 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('store', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Image de galerie', 'verbose_name_plural': 'Images de galerie'},
        ),
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Avis', 'verbose_name_plural': 'Avis'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variation', 'verbose_name_plural': 'Variations'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_promo',
            field=models.BooleanField(default=False, verbose_name='En promotion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de la promotion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Début de la promotion'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='is_promo',
            field=models.BooleanField(default=False, verbose_name='En promotion'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='promo_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de la promotion'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='promo_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Prix promotionnel'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='promo_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Début de la promotion'),
        ),
    ]
