# Generated by Django 5.2.3 on 2025-11-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_productgallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_variations',
            field=models.BooleanField(default=False, help_text='Cochez si ce produit a des variations (conditionnement, etc.)', verbose_name='Produit avec variations'),
        ),
    ]
