# Generated by Django 5.2.3 on 2025-11-19 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_has_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_variations',
        ),
    ]
