# Generated by Django 3.1 on 2025-06-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_price',
            field=models.FloatField(default=0.0),
        ),
    ]
