# Generated by Django 3.1 on 2025-06-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_variation_variation_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('product', 'variation_category', 'variation_value')},
        ),
    ]
