# Generated by Django 5.2.3 on 2026-01-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_has_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='variation',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix promotionnel'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
