# Generated by Django 5.2.3 on 2026-01-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_price_alter_variation_promo_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='variation',
            name='promo_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Prix promotionnel'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_price',
            field=models.FloatField(default=0.0),
        ),
    ]
