# Generated by Django 3.1 on 2025-06-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20250613_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products'),
        ),
    ]
