# Generated by Django 5.2.3 on 2025-08-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='subject',
        ),
    ]
