# Generated by Django 5.2.3 on 2025-11-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Bayer, Syngenta, Yara...', max_length=100, verbose_name='Nom du partenaire')),
                ('slug', models.SlugField(blank=True, help_text='Laisser vide → sera généré automatiquement', max_length=100, unique=True)),
                ('logo', models.ImageField(help_text='Format recommandé : PNG transparent ou JPG blanc – 300x150px max', upload_to='partners/logos/', verbose_name='Logo du partenaire')),
                ('website', models.URLField(blank=True, help_text='Ex: https://www.bayer.com (avec https://)', null=True, verbose_name='Site web officiel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Afficher sur le site')),
                ('order', models.PositiveIntegerField(default=0, help_text='Plus le nombre est petit → plus il apparaît en premier', verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['order', 'name'],
            },
        ),
    ]
