# Generated by Django 5.2.3 on 2025-11-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name="Titre (affiché sur l'image)")),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sous-titre')),
                ('button_text', models.CharField(default='Découvrir', max_length=50, verbose_name='Texte du bouton')),
                ('button_link', models.CharField(default='/store/', max_length=200, verbose_name='Lien du bouton')),
                ('image', models.ImageField(upload_to='home/carousel/', verbose_name='Image du carousel')),
                ('is_active', models.BooleanField(default=True, verbose_name="Afficher sur la page d'accueil")),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image Carousel Accueil',
                'verbose_name_plural': 'Carousel Accueil',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
