# Generated by Django 5.2.3 on 2025-11-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_homecarousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecarousel',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Image du carousel', 'verbose_name_plural': 'Carousel Accueil'},
        ),
        migrations.RemoveField(
            model_name='homecarousel',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='homecarousel',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='homecarousel',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='homecarousel',
            name='title',
        ),
        migrations.AlterField(
            model_name='homecarousel',
            name='image',
            field=models.ImageField(help_text='Recommandé : 1920x800px minimum, format JPG/PNG', upload_to='home/carousel/', verbose_name='Image du carousel'),
        ),
        migrations.AlterField(
            model_name='homecarousel',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Plus petit = apparaît en premier', verbose_name="Ordre d'affichage"),
        ),
    ]
