# Generated by Django 5.2.3 on 2025-07-06 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Livraison',
            new_name='livraison',
        ),
    ]
