# Generated by Django 5.2.3 on 2025-07-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_livraison_order_livraison'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='country',
            new_name='city',
        ),
    ]
