# Generated by Django 5.2.3 on 2025-08-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderproduct_user'),
        ('store', '0008_alter_product_id_alter_variation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='conditionnement',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
